version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: kc-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5434:5432" # puerto local para no chocar con tu postgres app
    volumes:
      - kc_pg_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    command:
      - start-dev
      - --http-port=8081
      - --proxy-headers=xforwarded
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
    volumes:
      - ../themes/ssu:/opt/keycloak/themes/ssu 
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - postgres

volumes:
  kc_pg_data:
